### ISSUE TITLE
Unify user methods

### ISSUE THREAD

**Issue by tombeynon** [rawnet/rawnet-admin#9]
The current default config sets the following..

```
config.user_method = :current_user
config.authenticate_method = :authenticate_admin!
```

We should probably unify the noun. Given that it's `RawnetAdmin` and not `RawnetUser`, shall we go with `admin`?

```
config.user_method = :current_admin
config.authenticate_method = :authenticate_admin!
```

**Comment by vertism** [comment]
Maybe go with user? You could have instances where there are different levels of access, and whilst all people being authenticated will be users, they may not all be admins.

**Comment by efexen** [comment]
I think user_method should be current_user as this is the practise most auth libs seem to follow, as for the authentication_method I like authenticate_admin as the area we're protecting is admin.

**Comment by tombeynon** [comment]
Cool, in that case let's leave it as is!
